/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary": "#ffffff",
        "tertiary": "#693600",
        "surface-container-low": "#eff4ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#000b62",
        "error": "#ba1a1a",
        "primary": "#1e30b2",
        "outline": "#757685",
        "primary-fixed": "#dfe0ff",
        "on-tertiary-fixed": "#2f1500",
        "on-surface-variant": "#454654",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffc89e",
        "on-secondary-container": "#006f66",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed-variant": "#2335b5",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#005049",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary": "#006a61",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "primary-container": "#3b4cca",
        "inverse-primary": "#bcc2ff",
        "surface-container": "#e5eeff",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-container": "#8b4a00",
        "on-secondary-fixed": "#00201d",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#86f2e4",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "outline-variant": "#c5c5d6",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#89f5e7",
        "surface": "#f8f9ff",
        "surface-tint": "#3f50ce",
        "secondary-fixed-dim": "#6bd8cb",
        "primary-fixed-dim": "#bcc2ff",
        "on-primary-container": "#ccd0ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "xs": "4px",
        "sm": "8px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
